apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
- ../common/cert-manager/cert-manager-kube-system-resources/base
- ../common/cert-manager/cert-manager-crds/base
- ../common/cert-manager/cert-manager/overlays/self-signed
# Istio
- ../common/istio-1-9-0/istio-crds/base
- ../common/istio-1-9-0/istio-namespace/base
- ../common/istio-1-9-0/istio-install/base
# OIDC Authservice
- ../common/oidc-authservice/base
# Dex
- ../common/dex/overlays/istio
# KNative
#- ../common/knative/knative-serving-crds/base
#- ../common/knative/knative-serving-install/base
#- ../common/knative/knative-eventing-crds/base
#- ../common/knative/knative-eventing-install/base
#- ../common/istio-1-9-0/cluster-local-gateway/base
# Kubeflow namespace
- ../common/kubeflow-namespace/base
# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-9-0/kubeflow-istio-resources/base


# Kubeflow Pipelines
- ../apps/pipeline/upstream/env/platform-agnostic-multi-user-pns
# KFServing
#- ../apps/kfserving/upstream/overlays/kubeflow
# Katib
#- ../apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../apps/centraldashboard/upstream/overlays/istio
# Admission Webhook
- ../apps/admission-webhook/upstream/overlays/cert-manager
# Notebook Controller
- ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Jupyter Web App
- ../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Web App
-  ../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Controller
-  ../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# TFJob Operator
- ../apps/tf-training/upstream/overlays/kubeflow
# Pytorch Operator
#- ../apps/pytorch-job/upstream/overlays/kubeflow
# MPI Operator
#- ../apps/mpi-job/upstream/overlays/kubeflow
# MXNet Operator
#- ../apps/mxnet-job/upstream/overlays/kubeflow
# XGBoost Operator
#- ../apps/xgboost-job/upstream/overlays/kubeflow

# User namespace
- ../common/user-namespace/base

# HTTPS
- certificate.yaml

configMapGenerator:
  - name: global-parameters
    env: global-params.env
  - name: pipeline-install-config
    env: pipeline-params.env
    behavior: merge
  - name: jupyter-web-app-config
    namespace: kubeflow
    behavior: merge
    files:
    - spawner_ui_config.yaml
  - name: kubeflow-pipelines-profile-controller-code
    namespace: kubeflow
    behavior: replace
    files:
    - sync.py

vars:
- name: externalIpAddress
  objref:
    kind: ConfigMap
    name: global-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.externalIpAddress

configurations:
- global-params.yaml

patchesStrategicMerge:
- set_memory.yaml
- workflow-controller-deployment-patch.yaml
- rewire_istio_images.yaml
- kf-istio-resources.yaml

images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: quay.io/ibm/kubeflow-oidc-authservice-ppc64le
  newTag: 28c59ef
- name: quay.io/dexidp/dex
  newName: quay.io/ibm/kubeflow-dex-ppc64le
  newTag: v2.24.0
- name: gcr.io/ml-pipeline/workflow-controller
  newName: quay.io/ibm/kubeflow-workflow-controller-ppc64le
  newTag: v2.12.9
- name: gcr.io/ml-pipeline/argoexec
  newName: quay.io/ibm/kubeflow-argoexec-ppc64le
  newTag: v2.12.9
- name: gcr.io/tfx-oss-public/ml_metadata_store_server
  newName: quay.io/ibm/kubeflow-ml_metadata_store_server-ppc64le
  newTag: 0.25.1
- name: gcr.io/ml-pipeline/metadata-envoy
  newName: quay.io/ibm/kubeflow-metadata-envoy-ppc64le
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/minio
  newName: quay.io/ibm/kubeflow-minio-ppc64le
  newTag: RELEASE.2019-04-09T01-22-30Z.1
- name: gcr.io/ml-pipeline/mysql
  newName: quay.io/ibm/kubeflow-mariadb-ppc64le
  newTag: 10.2.19
- name: python
  newName: registry.access.redhat.com/ubi8/python-38
  newTag: 1-75
- name: metacontroller/metacontroller:v0.3.0
  newName: quay.io/ibm/kubeflow-metacontroller-ppc64le
  newTag: v0.3.0
- name: gcr.io/ml-pipeline/api-server
  newName: quay.io/ibm/kubeflow-api-server-ppc64le
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/persistenceagent
  newName: quay.io/ibm/kubeflow-persistenceagent-ppc64le
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/scheduledworkflow
  newName: quay.io/ibm/kubeflow-scheduledworkflow-ppc64le
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/frontend
  newName: quay.io/ibm/kubeflow-frontend-ppc64le
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/viewer-crd-controller
  newName: quay.io/ibm/kubeflow-viewer-crd-controller-ppc64le
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/visualization-server
  newName: quay.io/ibm/kubeflow-visualization-server-ppc64le
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/metadata-writer
  newName: quay.io/ibm/kubeflow-metadata-writer-ppc64le
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/cache-deployer
  newName: quay.io/ibm/kubeflow-cache-deployer-ppc64le
  newTag: 1.5.0
- name: gcr.io/ml-pipeline/cache-server
  newName: quay.io/ibm/kubeflow-cache-server-ppc64le
  newTag: 1.5.0
- name: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newName: quay.io/ibm/kubeflow-access-management-ppc64le
  newTag: v1.3.0-rc.1
- name: public.ecr.aws/j1r0q0g6/notebooks/profile-controller 
  newName: quay.io/ibm/kubeflow-profile-controller-ppc64le
  newTag: v1.3.0-rc.1
- name: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard
  newName: quay.io/ibm/kubeflow-central-dashboard-ppc64le
  newTag: v1.3.0-rc.1
- name: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook
  newName: quay.io/ibm/kubeflow-admission-webhook-ppc64le
  newTag: v1.3.0-rc.1
- name: quay.io/jetstack/cert-manager-controller
  newName: quay.io/ibm/cert-manager-controller-ppc64le
  newTag: v0.11.0
- name: quay.io/jetstack/cert-manager-webhook
  newName: quay.io/ibm/cert-manager-webhook-ppc64le
  newTag: v0.11.0
- name: quay.io/jetstack/cert-manager-cainjector
  newName: quay.io/ibm/cert-manager-cainjector-ppc64le
  newTag: v0.11.0
- name: docker.io/istio/install-cni
  newName: quay.io/ibm/istio-install-cni-ppc64le
  newTag: 1.9.2
- name: docker.io/istio/proxyv2
  newName: quay.io/ibm/istio-proxyv2-ppc64le
  newTag: 1.9.2
- name: docker.io/istio/pilot
  newName: quay.io/ibm/istio-pilot-ppc64le
  newTag: 1.9.2
- name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
  newName: quay.io/ibm/kubeflow-jupyter-web-app-ppc64le
  newTag: v1.3.0-rc.1
- name: quay.io/kubeflow/tf-notebook-image
  newName: quay.io/ibm/kubeflow-notebook-image-ppc64le
  newTag: tensorflow-1.15.4-cpu-py3.6
- name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
  newName: quay.io/ibm/kubeflow-notebook-controller-ppc64le
  newTag: v1.3.0-rc.1
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
  newName: quay.io/ibm/kubeflow-tensorboards-web-app-ppc64le
  newTag: v1.3.0-rc.1
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboard-controller
  newName: quay.io/ibm/kubeflow-tensorboard-controller-ppc64le
  newTag: v1.3.0-rc.1
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: quay.io/brancz/kube-rbac-proxy
  newTag: v0.6.0-ppc64le
- name: public.ecr.aws/j1r0q0g6/training/tf-operator
  newName: quay.io/ibm/kubeflow-tf-operator-ppc64le
  newTag: cd2fc1ff397b1f349f68524f4abd5013a32e3033
- name: public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app
  newName: quay.io/ibm/kubeflow-volumes-web-app-ppc64le
  newTag: v1.3.0-rc.1
