apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
# Cert-Manager
# -> Using OpenShift cert-manager Operator
#- ../common/cert-manager/cert-manager/base
#- ../common/cert-manager/kubeflow-issuer/base
# Istio
# -> Using OpenShift Service Mesh Operator
#- ../common/istio-1-9/istio-crds/base
#- ../common/istio-1-9/istio-namespace/base
#- ../common/istio-1-9/istio-install/base
- allow-apiserver-webhooks.yaml
- allow-from-default-namespace.yaml
# OIDC Authservice
# -> Using OpenShift OAuth
#- ../common/oidc-authservice/base
# Dex
# -> Using OpenShift OAuth
#- ../common/dex/overlays/istio
# KNative
# -> Not supported yet (only needed for KServ)
#- ../common/knative/knative-serving/overlays/gateways
#- ../common/knative/knative-eventing/base
#- ../common/istio-1-9/cluster-local-gateway/base
# User namespace
# -> Using OpenShift namespace configuration Operator for user onboarding
#- ../common/user-namespace/base
- onboarding
