apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- namespace.yaml
- configmap.yaml
- clusterrolebinding.yaml
- controlplane.yaml
- route.yaml
- envoyfilters.yaml
- oauth-client.yaml 
- servicemeshmemberroll.yaml
- servicemeshmember.yaml

commonLabels:
  app.kubernetes.io/part-of: kubeflow

secretGenerator:
- name: oauth2-proxy
  envs:
  - oauth2-proxy.env
  type: Opaque

configMapGenerator:
- name: global-parameters
  env: global-params.env

replacements:
- source:
    kind: ConfigMap
    name: global-parameters
    version: v1
    fieldPath: data.clusterDomain
  targets:
  - select:
      kind: OAuthClient
      name: kubeflow-istio
    fieldPaths:
      - redirectURIs.0
    options:
      delimiter: '.'
      index: 1
  - select:
      kind: Route
      name: secure-kubeflow
    fieldPaths:
      - spec.host
    options:
      delimiter: '.'
      index: 1

configurations:
- transformers.yaml
