apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- kubeadminprofile.yaml
- kubeflow-profile-creation.yaml
- kubeflow-profile-namespace-config.yaml

commonLabels:
  app.kubernetes.io/part-of: kubeflow
