apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
# Cert-Manager
- ../common/cert-manager/cert-manager/base
- ../common/cert-manager/kubeflow-issuer/base
# Istio
- ../common/istio-1-9/istio-crds/base
- ../common/istio-1-9/istio-namespace/base
- ../common/istio-1-9/istio-install/base
# OIDC Authservice
- ../common/oidc-authservice/base
# Dex
- ../common/dex/overlays/istio

# User namespace
- ../common/user-namespace/base

# HTTPS
- certificate.yaml

configMapGenerator:
  - name: global-parameters
    env: global-params.env

vars:
- name: externalIpAddress
  objref:
    kind: ConfigMap
    name: global-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.externalIpAddress

configurations:
- global-params.yaml

patchesStrategicMerge:
- kf-istio-resources.yaml

images:
- name: quay.io/jetstack/cert-manager-controller
  newName: quay.io/ibm/cert-manager-controller-ppc64le
  newTag: v1.3.1
- name: quay.io/jetstack/cert-manager-webhook
  newName: quay.io/ibm/cert-manager-webhook-ppc64le
  newTag: v1.3.1
- name: quay.io/jetstack/cert-manager-cainjector
  newName: quay.io/ibm/cert-manager-cainjector-ppc64le
  newTag: v1.3.1
- name: docker.io/istio/proxyv2
  newName: quay.io/ibm/istio-proxyv2-ppc64le
  newTag: 1.9.6
- name: docker.io/istio/pilot
  newName: quay.io/ibm/istio-pilot-ppc64le
  newTag: 1.9.6
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: quay.io/ibm/kubeflow-oidc-authservice-ppc64le
  newTag: 28c59ef
- name: quay.io/dexidp/dex
  newName: quay.io/ibm/kubeflow-dex-ppc64le
  newTag: v2.24.0
