apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Elasticsearch.v1.logging.openshift.io,Kibana.v1.logging.openshift.io
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: GroupConfig.v1alpha1.redhatcop.redhat.io,NamespaceConfig.v1alpha1.redhatcop.redhat.io,UserConfig.v1alpha1.redhatcop.redhat.io
  name: namespace-configuration-operator
  namespace: namespace-configuration-operator
spec: {}
