apiVersion: redhatcop.redhat.io/v1alpha1
kind: UserConfig
metadata:
  name: kubeflow-user
spec:
  providerName: Local Password
  #name: {{ index (lookup "user.openshift.io/v1" "Identity" "" (index .Identities 0)).Extra "email" }}
  templates:
  - objectTemplate: |
      apiVersion: kubeflow.org/v1beta1
      kind: Profile
      metadata:
        name: {{ .Name | lower | replace "." "-" | replace "@" "-" | trimAll "."}}
      spec:
        owner:
          kind: User
          name: {{ .Name }}
        resourceQuotaSpec:
          hard:
            cpu: "20"
            memory: 64Gi
            "requests.nvidia.com/gpu": "2"
            persistentvolumeclaims: "100"
            requests.storage: "500Gi"
  - objectTemplate: | 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: editor-for-{{ .Name | lower | replace "." "-" | replace "@" "-" | trimAll "."}}
        namespace: kubeflow
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: kubeflow-edit
      subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: {{ .Name }}
  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: system:openshift:scc:privileged
        namespace: {{ .Name | lower | replace "." "-" | replace "@" "-" | trimAll "." }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:openshift:scc:privileged
      subjects:
      - kind: ServiceAccount
        name: default-editor
        namespace: {{ .Name | lower | replace "." "-" | replace "@" "-" | trimAll "." }}
  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: kubeflow-editor
        namespace: {{ .Name | lower | replace "." "-" | replace "@" "-" | trimAll "." }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: kubeflow-edit
      subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: {{ .Name }} 
  - objectTemplate: | 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: {{ .Name | lower | replace "." "-" | replace "@" "-" | trimAll "." }}-sm-view
        namespace: istio-system
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: view
      subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: {{ .Name }}
  - objectTemplate: |
      apiVersion: networking.istio.io/v1alpha3
      kind: EnvoyFilter
      metadata:
        name: add-header
        namespace: {{ .Name | lower | replace "." "-" | replace "@" "-" | trimAll "." }}
      spec:
        configPatches:
        - applyTo: VIRTUAL_HOST
          match:
            context: SIDECAR_OUTBOUND
            routeConfiguration:
              vhost:
                name: ml-pipeline.kubeflow.svc.cluster.local:8888
                route:
                  name: default
          patch:
            operation: MERGE
            value:
              request_headers_to_add:
              - append: true
                header:
                  key: kubeflow-userid
                  value: {{ .Name }}
