apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    istio-injection: enabled
---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
spec:
  baseImage: quay.io/mgiessing/grafana:7.5.15
  # https://github.com/grafana/grafana/blob/main/conf/defaults.ini
  config:
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.proxy:
      auto_sign_up: true
      enabled: true
      header_name: kubeflow-userid
      header_property: username
    log:
      level: debug
      mode: console
    security:
      admin_password: admin
      admin_user: admin
      allow_embedding: true
    server:
      root_url: /grafana
      serve_from_sub_path: true
    users:
      auto_assign_org: false
      default_theme: light
  dashboardLabelSelector:
  - matchExpressions:
    - key: app
      operator: In
      values:
      - grafana
  dataStorage:
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  ingress:
    enabled: true
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: grafana
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /grafana/
    rewrite:
      uri: /grafana/
    route:
    - destination:
        host: grafana-service.grafana.svc.cluster.local
        port:
          number: 3000
