apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tensorboards-web-app-kubeflow-tensorboard-ui-edit
rules:
- apiGroups:
  - tensorboard.kubeflow.org
  resources:
  - tensorboards
  - tensorboards/finalizers
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - watch
